// Vendors open-licence (OFL) web fonts from Google Fonts into
// bundles/rashinban/graphics/assets/fonts/ so overlays work offline.
// Produces fonts.css with @font-face rules pointing at local woff2 files.
// Run once: `node scripts/fetch-fonts.mjs`.
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = "bundles/rashinban/graphics/assets/fonts";
const FAMILIES = ["Oswald:wght@500;700", "Noto+Sans+JP:wght@400;700"];
// A modern UA makes Google return woff2 with unicode-range subsets.
const UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

mkdirSync(OUT, { recursive: true });
let css = "/* Generated by scripts/fetch-fonts.mjs. Fonts are OFL-licensed (Google Fonts). */\n";
let count = 0;
for (const family of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${family}&display=swap`;
  const text = await (await fetch(url, { headers: { "User-Agent": UA } })).text();
  const rewritten = await replaceAsync(text, /url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g, async (_m, src) => {
    const name = src.split("/").slice(-2).join("-");
    const res = await fetch(src);
    if (!res.ok) throw new Error(`${src}: HTTP ${res.status}`);
    writeFileSync(path.join(OUT, name), Buffer.from(await res.arrayBuffer()));
    count++;
    return `url(${name})`;
  });
  css += `\n/* ${family} */\n${rewritten}`;
}
writeFileSync(path.join(OUT, "fonts.css"), css);
console.log(`wrote ${count} font files and fonts.css into ${OUT}`);

async function replaceAsync(str, re, fn) {
  const parts = [];
  let last = 0;
  for (const m of str.matchAll(re)) {
    parts.push(str.slice(last, m.index), await fn(...m));
    last = m.index + m[0].length;
  }
  parts.push(str.slice(last));
  return parts.join("");
}
